import 'package:flutter/material.dart';
import '../locator.dart';
import '../models/lead.dart';
import '../utils/formatters.dart';
import '../viewmodels/lead_viewmodel.dart';

class AddFollowUpScreen extends StatefulWidget {
  final Lead lead;

  const AddFollowUpScreen({super.key, required this.lead});

  @override
  State<AddFollowUpScreen> createState() => _AddFollowUpScreenState();
}

class _AddFollowUpScreenState extends State<AddFollowUpScreen> {
  LeadChannel? _selectedChannel;
  bool _responded = false;
  bool _isSaving = false;
  final _leadViewModel = locator<LeadViewModel>();
  final _noteController = TextEditingController();

  @override
  void dispose() {
    _noteController.dispose();
    super.dispose();
  }

  Future<void> _save() async {
    if (_selectedChannel == null) return;

    setState(() => _isSaving = true);

    final followUp = FollowUp(
      id: '', // ID will be generated by the repository '',
      leadId: widget.lead.id,
      timestamp: DateTime.now(),
      channel: _selectedChannel!,
      responded: _responded,
      note: _noteController.text.trim(),
    );

    try {
      await _leadViewModel.addFollowUp(followUp);
      if (mounted) Navigator.of(context).pop();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Failed to save follow-up: $e')));
      }
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Add Follow-Up')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            DropdownButtonFormField<LeadChannel>(
              initialValue: _selectedChannel,
              decoration: const InputDecoration(labelText: 'Channel *'),
              items: LeadChannel.values
                  .map(
                    (ch) => DropdownMenuItem(
                      value: ch,
                      child: Text(formatEnum(ch.name)),
                    ),
                  )
                  .toList(),
              onChanged: (ch) => setState(() => _selectedChannel = ch),
            ),
            const SizedBox(height: 16),
            SwitchListTile(
              title: const Text('Did they respond?'),
              value: _responded,
              onChanged: (val) => setState(() => _responded = val),
            ),
            const SizedBox(height: 16),
            TextFormField(
              controller: _noteController,
              decoration: const InputDecoration(labelText: 'Notes (optional)'),
              maxLines: 3,
            ),
            const SizedBox(height: 32),
            FilledButton(
              onPressed: (_isSaving || _selectedChannel == null) ? null : _save,
              child: _isSaving
                  ? const SizedBox(
                      height: 20,
                      width: 20,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : const Text('Save Follow-Up'),
            ),
          ],
        ),
      ),
    );
  }
}
