import 'package:flutter/material.dart';
import 'package:lead_tracker/viewmodels/lead_viewmodel.dart';
import '../models/lead.dart';
import '../locator.dart';

class AddLeadScreen extends StatefulWidget {
  const AddLeadScreen({super.key});

  @override
  State<AddLeadScreen> createState() => _AddLeadScreenState();
}

class _AddLeadScreenState extends State<AddLeadScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _phoneController = TextEditingController();
  final _emailController = TextEditingController();
  final _messageController = TextEditingController();
  LeadChannel _selectedChannel = LeadChannel.website;
  bool _isSaving = false;
  final _leadViewModel = locator<LeadViewModel>();

  @override
  void dispose() {
    _nameController.dispose();
    _phoneController.dispose();
    _emailController.dispose();
    _messageController.dispose();
    super.dispose();
  }

  Future<void> _saveLead() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isSaving = true);

    final lead = Lead(
      id: '', // ID will be generated by the repository
      name: _nameController.text.trim(),
      phone: _phoneController.text.trim(),
      email: _emailController.text.trim(),
      message: _messageController.text.trim(),
      channel: _selectedChannel,
      status: LeadStatus.fresh,
      timestamp: DateTime.now(),
    );

    try {
      await _leadViewModel.addLead(lead);
      if (mounted) Navigator.of(context).pop();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Failed to save lead: $e')));
      }
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Add Lead')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Name *'),
                textCapitalization: TextCapitalization.words,
                validator: (v) =>
                    (v == null || v.trim().isEmpty) ? 'Name is required' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _phoneController,
                decoration: const InputDecoration(labelText: 'Phone *'),
                keyboardType: TextInputType.phone,
                validator: (v) => (v == null || v.trim().isEmpty)
                    ? 'Phone is required'
                    : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _emailController,
                decoration: const InputDecoration(labelText: 'Email'),
                keyboardType: TextInputType.emailAddress,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _messageController,
                decoration: const InputDecoration(labelText: 'Message'),
                maxLines: 3,
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<LeadChannel>(
                initialValue: _selectedChannel,
                decoration: const InputDecoration(labelText: 'Channel'),
                items: LeadChannel.values
                    .map(
                      (ch) => DropdownMenuItem(
                        value: ch,
                        child: Text(_channelLabel(ch)),
                      ),
                    )
                    .toList(),
                onChanged: (ch) {
                  if (ch != null) setState(() => _selectedChannel = ch);
                },
              ),
              const SizedBox(height: 32),
              FilledButton(
                onPressed: _isSaving ? null : _saveLead,
                child: _isSaving
                    ? const SizedBox(
                        height: 20,
                        width: 20,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Text('Save Lead'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  String _channelLabel(LeadChannel channel) => switch (channel) {
    LeadChannel.website => 'Website',
    LeadChannel.socialMedia => 'Social Media',
    LeadChannel.sms => 'SMS',
    LeadChannel.email => 'Email',
    LeadChannel.phone => 'Phone',
  };
}
